apiVersion: v1
kind: Pod
metadata:
  name: lamp
spec:
  containers:
  - name: web
    image: wancasfer/lamp:latest
    ports:
    - containerPort: 80
    env:
    - name: MARIADB_HOSTNAME
      value: "mariadb"
    - name: MARIADB_USERNAME
      value: "root"
    - name: MARIADB_PASSWORD
      value: "root"
  - name: mariadb
    image: mariadb:10.6
    ports:
    - containerPort: 3306
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "root"
