apiVersion: v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
    
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx:1.21
        ports:
        - containerPort: 80
